server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharedlife?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

MD5Salt: wyt
imageFilePath: P:\\MyProject\\working\\sharedlife\\src\\main\\webapp\\static\\images\\
downloadImagePath: P:\\MyProject\\working\\sharedlife\\src\\main\\webapp
lucenePath: P:\\MyProject\\working\\sharedlife\\lucene